# Autogenerated by nbdev

d = { 'settings': {'branch': '', 'doc_baseurl': '/', 'doc_host': 'https://.github.io', 'git_url': 'https://github.com//', 'lib_path': ''},
  'syms': {'wbdev_card.core': {'wbdev_card.core.foo': ('core.html#foo', 'wbdev_card/core.py')}, 'wbdev_card.setup': {}}}
